# Generated by Django 3.0.4 on 2021-02-19 23:56

import core.erp.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[core.erp.validators.vcedula], verbose_name='Cédula')),
                ('names', models.CharField(max_length=150, validators=[core.erp.validators.validarLetrass], verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, validators=[core.erp.validators.validarLetras], verbose_name='Apellidos')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
