# Generated by Django 3.0.4 on 2021-02-20 00:13

import core.erp.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, validators=[core.erp.validators.validarLetrass], verbose_name='Nombres')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('especie', models.CharField(choices=[('perro', 'perro'), ('gato', 'gato')], default='perro', max_length=10, verbose_name='Especie')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mascot/%Y/%m/%d')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['id'],
            },
        ),
    ]
