# Generated by Django 3.0.4 on 2021-02-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_mascot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascot',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='names',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
    ]
