# Generated by Django 3.0.4 on 2021-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_mascot_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telefono',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='mascot',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='especie',
            field=models.CharField(choices=[('PERRO', 'PERRO'), ('GATO', 'GATO')], default='perro', max_length=10, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='gender',
            field=models.CharField(choices=[('male', 'MACHO'), ('female', 'HEMBRA')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascot/%Y/%m/%d', verbose_name='Dueño'),
        ),
    ]
