# Generated by Django 3.0.4 on 2021-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20210223_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascot',
            name='observacion',
            field=models.CharField(default=1, max_length=100, verbose_name='Observacion'),
            preserve_default=False,
        ),
    ]
