# Generated by Django 3.0.4 on 2021-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210223_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascot',
            name='image',
            field=models.ImageField(default=1, upload_to='mascot/%Y/%m/%d', verbose_name='Imagen Mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascot',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion'),
        ),
    ]
