# Generated by Django 3.0.4 on 2021-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210223_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascot',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza'),
        ),
    ]
